name: discord_bot
description: A sample command-line application.
version: 1.0.0
environment:
  sdk: ^2.18.5

# Add regular dependencies here

dependencies:
  nyxx: ^5.1.0
  nyxx_commands: ^5.0.2
  nyxx_extensions: ^3.2.0
  nyxx_lavalink: ^3.2.0
  nyxx_pagination: ^2.4.0
# path: ^1.8.0
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
