name: discord_bot
description: A sample command-line application.
version: 1.0.0
environment:
  sdk: ^2.18.5

# Add regular dependencies here

dependencies:
  nyxx: ^5.1.0
  nyxx_commands: ^5.0.2
  nyxx_extensions: ^3.2.0
  nyxx_lavalink: ^3.2.0
  nyxx_pagination: ^2.4.0
# path: ^1.8.0
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: [2.19.0, stable]
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: dart test
